#!/usr/bin/env bash
# This is for task 0

usage="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

[[ $# != 4 ]] && echo "$usage" && exit

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":/home/"$3"
