#!/usr/bin/env bash
# Configuring ubuntu to instal nginx

echo "installing Nginx, please wait...."

sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

echo "we are almost done, do not interupt"
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
