#!/usr/bin/env bash
# Configuring ubuntu to instal nginx

echo "installing Nginx, please wait...."

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

echo "we are almost done, do not interupt"
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx.html /var/www/html/index.nginx.html.bckp

echo "Hello World!" | sudo dd status=none of=/var/www/html/index.nginx.html

sudo service nginx restart
