#!/usr/bin/env bash
# Conguring ubuntu for redrection

echo "Please wait Nginx is being installed"
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

echo "We are almost done..."

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx.html /var/www/html/index.nginx.html.bckp

echo "Hello World!" > /var/www/html/index.nginx.html
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart
