#!/usr/bin/env bash
# Updating redirecting of url
apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html

REDIRECT='rewrite ^/redirect_me https://github.com/Udoozy permanent;'
NGINX_CONF='/etc/nginx/sites-available/default'
cp $NGINX_CONF ${NGINX_CONF}.bak
sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\t'"$REDIRECT"'\n\t}' $NGINX_CONF
nginx -s reload

curl -sI localhost/redirect_me | grep "301 Moved Permanently" > /dev/null
