#!/usr/bin/env bash
# Configuring server web-01 and web-0 to handle load balancing
host_var=$(hostname)
err_page="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
header_page="server {\n\tadd_header X-Served-By $host_var;"

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$err_page/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$header_page/" /etc/nginx/sites-available/default

sudo service nginx start
