#!/usr/bin/env bash
# Configuring server web-01 and web-0 to handle load balancing

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html

REDIRECT='\\trewrite ^/redirect_me https://github.com/Udoozy permanent;'
filePath='/etc/nginx/sites-available/default'
sed -i '30i\\t#Permanent redirects' $filePath
sed -i '31i\\t#' $filePath
sed -i "32i $REDIRECT" $filePath
sed -i '33i \\t' $filePath

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/html/; internal; }' $filePath

HEADER_HOSTNAME='\\t add_header X-Served-By'

sed -i '34i\\t#HTTP HEADER CONFIGURATION' $filePath
sed -i '35i\\t#' $filePath
sed -i "36i $HEADER_HOSTNAME ${HOSTNAME};" $filePath
sed -i '37i \\t' $filePath

service nginx restart
