#!/usr/bin/env bash
# This installs and configure HAPROXY on my web server

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "EOM" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 345503-web-01 54.145.156.219 check
   server 345503-web-02 18.233.67.185 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
