#!/usr/bin/env bash
#This terminates the 4-to_infinity_and_beyond process

pid=$(pgrep -f 4-to_infinity_and_beyond)

if [ -n "$pid" ]; then
    kill -15 "$pid"
else
    echo "No 4-to_infinity_and_beyond process found"
fi