#!/usr/bin/env bash
#This script display /etc/passwd story

file="/etc/passwd"

while IFS=: read -r username g_id home cmd u_id pass u_info

do
	echo "The user $username is part of the $g_id gang, lives in $home and rides $cmd. $u_id's place is protected by the passcode $pass, more info about the user here: $u_info"

done < "$file"
