#!/usr/bin/env bash
#This script list formated file in current directed

file=school

	if [ ! -e $file ]
	then
		echo "school file does not exist"
		exit 0
	fi

	echo "school file exists"

	if [ -s $file ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi


	if [ ! -d $file ]
	then 
		echo "school is a regular file"
	fi
